RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Models/Atividade.cs
using System;
using System.Collections.Generic;

namespace sistema.Models;

public partial class Atividade
{
    public int AtividadeId { get; set; }

    public string? Descricao { get; set; }

    public int? TurmaId { get; set; }

    public virtual Turma? Turma { get; set; }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Models/ErrorViewModel.cs
namespace sistema.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Models/Professor.cs
using System;
using System.Collections.Generic;

namespace sistema.Models;

public partial class Professor
{
    public int ProfessorId { get; set; }

    public string? Nome { get; set; }

    public string? Email { get; set; }

    public string? Senha { get; set; }

    public virtual ICollection<Turma> Turmas { get; set; } = new List<Turma>();
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Models/Turma.cs
using System;
using System.Collections.Generic;

namespace sistema.Models;

public partial class Turma
{
    public int TurmaId { get; set; }

    public string? Nome { get; set; }

    public int? ProfessorId { get; set; }

    public virtual ICollection<Atividade> Atividades { get; set; } = new List<Atividade>();

    public virtual Professor? Professor { get; set; }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Controllers/AtividadeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using sistema.Contexts;
using sistema.Models;

namespace sistema.Controllers
{
    public class AtividadeController : Controller
    {
        private readonly SistemaContext _context;

        public AtividadeController(SistemaContext context)
        {
            _context = context;
        }

        public IActionResult Index(int turmaId)
        {
            var atividades = _context.Atividades
                .Include(a => a.Turma)
                .Where(a => a.TurmaId == turmaId);

            var turma = _context.Turmas.FirstOrDefault(x => x.TurmaId == turmaId);

            ViewBag.TurmaId = turmaId;
            ViewBag.NomeTurma = turma!.Nome;

            ViewBag.NomeProfessor = HttpContext.Session.GetString("Nome");

            return View(atividades);

        }

        [HttpPost]
        public IActionResult CadastrarAtividade(int turmaId, string descricao)
        {
            var turma = _context.Turmas.FirstOrDefault(t => t.TurmaId == turmaId);

            if (turma == null)
            {
                return View();
            }

            var novaAtividade = new Atividade
            {
                Descricao = descricao,
                TurmaId = turmaId
            };

            _context.Atividades.Add(novaAtividade);

            _context.SaveChanges();

            return RedirectToAction("Index", "Atividades", new {turmaId});
        }

    }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using sistema.Models;
using System.Diagnostics;

namespace sistema.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using sistema.Contexts;

namespace sistema.Controllers
{
    public class LoginController : Controller
    {
        private readonly SistemaContext _context;
        public LoginController(SistemaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Logar(string email, string senha) 
        {
            var professor = _context.Professors.FirstOrDefault(p => p.Email == email && p.Senha == senha);

            if (professor != null)
            {
                HttpContext.Session.SetInt32("ProfessorId", professor.ProfessorId);
                HttpContext.Session.SetString("Nome", professor.Nome);

                return RedirectToAction("Index", "Professor");
               
            }

            TempData["Mensagem"] = "Email ou senha incorretos";

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Login");
        }
    }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using sistema.Contexts;
using sistema.Models;

namespace sistema.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly SistemaContext _context;

        public ProfessorController(SistemaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            int? professorId = HttpContext.Session.GetInt32("ProfessorId");

            if (professorId == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var professor = _context.Professors.Find(professorId);

            var turmas = _context.Turmas.Where(x => x.ProfessorId == professorId).ToList();

            ViewBag.NomeProfessor = professor!.Nome;

            return View(turmas);

        }

        [HttpPost]
        public IActionResult CadastrarTurma(string nomeTurma)
        {
            int? professorId = HttpContext.Session.GetInt32("ProfessorId");

            var turma = new Turma
            {
                Nome = nomeTurma,
                ProfessorId = professorId
            };

            _context.Turmas.Add(turma);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ExcluirTurma(int turmaId)
        {
            var turma = _context.Turmas.Include(t => t.Atividades).FirstOrDefault(t => t.TurmaId == turmaId);

            if (turma!.Atividades.Any())
            {
                TempData["Mensagem"] = "Você não pode exluir uma turma ocom atividades";

                return RedirectToAction("Index");
            }

            _context.Turmas.Remove(turma);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Views/Atividade/Index.cshtml
@{
    ViewData["Title"] = "Atividades";
}

@if(ViewBag.NomeProfessor == null)
{
    <a asp-controller="Login">Login</a>
}
else
{

    @*cabecalho*@


    @*cadastrar turma*@
    <form asp-controller="Atividade" asp-action="CadastrarAtividade">
        <input type="hidden" name="turmaId" value="@ViewBag.TurmaId" />

        <input type="text" required name="descricao" placeholder="Descricao da Atividade" />
        <button type="submit">Cadastrar atividade</button>
    </form>

    <h4>Turma: @ViewBag.NomeTurma</h4>


    @*tabela*@
    <table>
        <thead>
            <tr>
                <th>Número</th>
                <th>Nome da Atividade</th>

            </tr>
        </thead>

        <tbody>
            @foreach (var atividade in Model)
            {
                <tr>
                    <td>@atividade.AtividadeId</td>
                    <td>@atividade.Descricao</td>

                </tr>
            }

        </tbody>
    </table>
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}



<form asp-controller="Login" asp-action="Logar" method="post" class="w-50 p-5 mx-auto mt-5 shadow rounded d-flex flex-column align-items-center gap-4">

    <h2>Bem vindo</h2>

    <div class="w-100">
        <label class="form-label">Email</label>
        <input type="email" name="email" required class="form-control"/>
    </div>

    <div class="w-100">
        <label class="form-label">Senha</label>
        <input type="password" name="senha" required class="form-control"/>
    </div>

    <button class="btn btn-primary" type="submit">Entrar</button>
</form>

@if(TempData["Mensagem"] != null)
{
    <p class="text-center mt-5 text-danger">@TempData["Mensagem"]</p>
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Views/Professor/Index.cshtml
@{
    ViewData["Title"] = "Principal";
}

@if (ViewBag.NomeProfessor == null)
{
    <a asp-controller="Login">Login</a>
}
else
{

    @*cabecalho*@


    @*cadastrar turma*@


    <div class="d-flex mx-3 justify-content-between mt-3">
        <h3 class="fw-bold">Sua lista de turmas</h3>
        <button data-bs-toggle="modal" data-bs-target="#cadastrarTurma" type="button" class="btn btn-outline-primary">Cadastrar turma</button>
    </div>
    
  

    @*titulo*@


    @*tabela*@
    <table class="table">
        <thead>
            <tr>
                <th>Número</th>
                <th>Nome da Turma</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var turma in Model)
            {
                <tr>
                    <td>@turma.TurmaId</td>
                    <td>@turma.Nome</td>
                    <td>
                        <div style="display:flex">
                            <form asp-controller="Professor" asp-action="ExcluirTurma" onsubmit="return confirm('Você tem certeza que deseja excluir esta turma?')">
                                <input type="hidden" name="turmaId" value="@turma.TurmaId" />
                                <button type="submit" class="text-danger btn-link bg-white border-0">Excluir</button>
                            </form>

                            <form asp-controller="Atividade" asp-action="Index" asp-route-turmaId="@turma.TurmaId">
                                <input type="hidden" name="turmaId" value="@turma.TurmaId" />
                                <button type="submit" class="text-success btn-link bg-white border-0">Visualizar</button>
                            </form>
                        </div>


                    </td>
                </tr>
            }

        </tbody>
    </table>

    @if (TempData["Mensagem"] != null)
    {
        <p style="color:darkred">@TempData["Mensagem"]</p>
    }

    <div class="modal" tabindex="-1" id="cadastrarTurma">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Cadastrar Turma</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form asp-action="CadastrarTurma" asp-controller="Professor">
                <div class="modal-body">

                    <label class="form-label">Nome da Turma</label>
                    <input type="text" required name="nomeTurma" class="form-control" />
                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

RelembrandoMVC/Catarina Sayuri Arashiro Braga Felipe/sistema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sistema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sistema.styles.css" asp-append-version="true" />
</head>
<body>

    @if (ViewData["Title"] != "Login")
    {
    <header class="w-100 m-0 py-4 px-5 bg-primary">
        <div class="d-flex justify-content-between">
            <h3 class="text-light">@ViewBag.NomeProfessor</h3>
            <form asp-controller="Login" asp-action="Logout">
                <button class="btn btn-light" type="submit">Sair</button>
            </form>
        </div>
    </header>
    }

   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>